### ISSUE TITLE
cleaning up

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android-node#17]
- [ ] upgrade and clean up dependencies
- [ ] rename CA

**Comment by tomholub** [comment]
@Den I forgot to fix the "VERSION" button, currently it throws:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.flowcrypt.node, PID: 17714
    android.os.NetworkOnMainThreadException
        at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1317)
        at com.android.org.conscrypt.Platform.blockGuardOnNetwork(Platform.java:300)
        at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:741)
        at com.android.okhttp.okio.Okio$2.read(Okio.java:136)
        at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
        at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:50)
        at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:418)
        at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:360)
        at com.yourorg.sample.node.results.RawNodeResult.readOneUtfLineFromInputStream(RawNodeResult.java:86)
        at com.yourorg.sample.node.results.RawNodeResult.stripAndParseJsonResponseLineIfNotStrippedYet(RawNodeResult.java:113)
        at com.yourorg.sample.node.results.RawNodeResult.getErr(RawNodeResult.java:46)
        at com.yourorg.sample.MainActivity$6.onPostExecute(MainActivity.java:215)
        at com.yourorg.sample.MainActivity$6.onPostExecute(MainActivity.java:207)
        at android.os.AsyncTask.finish(AsyncTask.java:660)
        at android.os.AsyncTask.-wrap1(AsyncTask.java)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:677)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6123)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```

This is because `nodeResult.getErr()` and `nodeResult.getRawJsonResponse()` may pull data directly from the http socket.

I don't know if this is the best approach, and I may refactor it.

**Comment by tomholub** [comment]
@DenBond7 let me know if you have any feedback about how the encrypt and message results and errors are retrieved. Here is an example:

```Java
    DecryptMsgResult r = Node.decryptMsg(data, prvKeys, passphrases, null);
    if(r.getErr() != null) { // catch Node exception
      r.getErr().printStackTrace(); // NodeError
    } else if (r.getDecryptErr() != null) {
      System.out.println(r.getDecryptErr().type); // error type enum string
      System.out.println(r.getDecryptErr().error); // error as tring
    } else {
      // blockMetas = r.getAllBlockMetas(); // get info about all blocks
      PgpBlock block;
      while((block = r.getNextBlock()) != null) {
        if(block.getType().equals(MsgBlock.TYPE_HTML) {
          renderHtml(block.getContent());
        } else {
          // ...
        }
      }
    }
``` 

This will save you a lot of work because you get the decrypted message already converted to blocks, and it will seamlessly handle MIME messages, standard messages, etc. So less logic in Android, less calling back and forth to JS and more consistency with browser extension.

Decrypting file is simpler, because the result is just bytes:

```Java
    DecryptFileResult r = Node.decryptFile(encryptedData, prvKeys, passphrases, null);
    if(r.getErr() != null) {
      // ...
    } else if (r.getDecryptErr() != null) {
      // ...
    } else {
      // r.getName()
      // r.getDecryptedDataBytes() or getDecryptedByteStream()
    }

```
